from bridge import app, live_refresh_worker
from flask import Response
import threading
import os


PSYCHO_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>PSYCHO // PHASE 2</title>
<style>
:root{--bg:#050611;--panel:#0b0d1c;--panel2:#101329;--line:#262b4a;--text:#f5f7ff;--muted:#9298b8;--red:#ff245c;--pink:#ff3cac;--purple:#8b5cf6;--blue:#24d8ff;--green:#20f6a0;--yellow:#ffd166;--orange:#ff7a45}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#050611;color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}body{overflow-x:hidden;background:radial-gradient(ellipse at 15% 0%,#26114d 0%,transparent 35%),radial-gradient(ellipse at 90% 12%,#063b56 0%,transparent 30%),linear-gradient(135deg,#050611 0%,#08081a 48%,#050611 100%)}
body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.28;background-image:linear-gradient(rgba(67,84,140,.18) 1px,transparent 1px),linear-gradient(90deg,rgba(67,84,140,.18) 1px,transparent 1px);background-size:42px 42px;mask-image:linear-gradient(to bottom,#000,transparent 90%)}
body:after{content:"";position:fixed;inset:-30%;pointer-events:none;background:conic-gradient(from 180deg at 50% 50%,transparent,#ff245c18,transparent,#24d8ff18,transparent,#8b5cf618,transparent);animation:spin 18s linear infinite;filter:blur(35px)}@keyframes spin{to{transform:rotate(360deg)}}
.wrap{position:relative;z-index:1;max-width:1320px;margin:auto;padding:20px 24px 30px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:9px 0 18px;border-bottom:1px solid #303653}.brand{font-weight:1000;font-size:20px;letter-spacing:.16em;text-shadow:0 0 22px #ff245c55}.brand span{color:var(--pink)}.sub{font-size:10px;color:#8991b4;letter-spacing:.25em;margin-top:6px}.status{display:flex;align-items:center;gap:9px;padding:9px 14px;border:1px solid #324064;background:linear-gradient(135deg,#10152c,#090b18);border-radius:999px;font-size:10px;letter-spacing:.15em;box-shadow:0 0 22px #20f6a015}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 8px var(--green),0 0 22px #20f6a088}
.hero{position:relative;padding:55px 0 36px;min-height:300px;overflow:hidden}.hero:after{content:"";position:absolute;right:3%;top:20px;width:390px;height:230px;background:repeating-linear-gradient(135deg,transparent 0 18px,#24d8ff1c 19px 20px),linear-gradient(160deg,transparent 42%,#ff245c22 43% 44%,transparent 45%),linear-gradient(20deg,transparent 46%,#20f6a020 47% 48%,transparent 49%);transform:skewX(-18deg);filter:drop-shadow(0 0 20px #24d8ff22);opacity:.8}.eyebrow{position:relative;z-index:1;font-size:10px;letter-spacing:.32em;color:var(--blue);font-weight:900}.hero h1{position:relative;z-index:1;font-size:clamp(42px,8vw,92px);line-height:.88;margin:13px 0 17px;font-weight:1000;letter-spacing:-.065em}.hero h1 .hot{background:linear-gradient(90deg,#fff,#ff4d85,#a78bfa,#24d8ff);-webkit-background-clip:text;background-clip:text;color:transparent;text-shadow:0 0 45px #ff245c22}.hero h1 .outline{color:transparent;-webkit-text-stroke:1px #7881a7}.hero p{position:relative;z-index:1;max-width:700px;color:#aeb5d1;font-size:14px;line-height:1.75;margin:0}.hero .pulse{position:absolute;left:0;bottom:5px;width:100%;height:2px;background:linear-gradient(90deg,transparent,var(--red),var(--pink),var(--blue),transparent);box-shadow:0 0 16px #ff245c88;animation:pulse 2.8s ease-in-out infinite}@keyframes pulse{50%{opacity:.35;filter:blur(2px)}}
.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{position:relative;background:linear-gradient(145deg,#11152aee,#080a16ee);border:1px solid #2b3356;border-radius:15px;padding:18px;box-shadow:0 18px 50px #0008,0 0 30px #2430ff0a;overflow:hidden}.card:before{content:"";position:absolute;inset:0;background:linear-gradient(120deg,transparent 0 45%,#ffffff05 50%,transparent 55%);pointer-events:none}.label{font-size:9px;letter-spacing:.2em;color:#858dad;text-transform:uppercase}.value{font-size:24px;font-weight:950;margin-top:9px;letter-spacing:-.02em}.small{font-size:10px;color:#8189a9;margin-top:7px;line-height:1.5}.state{color:var(--green);text-shadow:0 0 14px #20f6a055}.section{margin-top:26px}.section-title{display:flex;align-items:center;gap:12px;font-size:10px;letter-spacing:.28em;color:#9ca5c8;margin-bottom:11px}.section-title:after{content:"";height:1px;flex:1;background:linear-gradient(90deg,#313b61,transparent)}
.market-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.market{min-height:230px}.market:after{content:"";position:absolute;right:-70px;bottom:-110px;width:260px;height:220px;border-radius:50%;background:radial-gradient(circle,#8b5cf622,transparent 67%);pointer-events:none}.nifty{border-top:2px solid var(--blue);box-shadow:0 18px 55px #0008,0 -4px 28px #24d8ff12}.bank{border-top:2px solid var(--pink);box-shadow:0 18px 55px #0008,0 -4px 28px #ff3cac12}.market-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:17px}.ticker{font-size:21px;font-weight:1000;letter-spacing:.05em}.ticker .spark{font-size:12px;margin-left:7px;color:var(--blue)}.bank .ticker .spark{color:var(--pink)}.pill{font-size:8px;padding:6px 9px;border-radius:999px;background:#151b31;color:#a9b1d0;border:1px solid #303b63;letter-spacing:.13em}.price{font-size:42px;font-weight:1000;letter-spacing:-.045em;background:linear-gradient(90deg,#fff,#c9d1ff);-webkit-background-clip:text;background-clip:text;color:transparent}.gap{font-size:10px;color:#9ca6c9;margin-top:4px}.row{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:18px}.mini{background:linear-gradient(145deg,#0c1122,#090b17);border:1px solid #242e50;border-radius:10px;padding:11px}.mini .label{color:#6f789a}.mini b{display:block;font-size:15px;margin-top:5px}.mini:nth-child(1) b{color:var(--blue)}.mini:nth-child(2) b{color:var(--green)}.mini:nth-child(3) b{color:var(--purple)}
.layers{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.layer{position:relative;padding:17px 10px;text-align:center;border:1px solid #293252;border-radius:11px;background:linear-gradient(180deg,#10152a,#090c18);overflow:hidden}.layer:before{content:"";position:absolute;left:0;right:0;top:0;height:2px;background:linear-gradient(90deg,var(--blue),var(--purple),var(--pink));opacity:.7}.layer strong{display:block;font-size:17px}.layer span{font-size:8px;color:#7882a5;letter-spacing:.14em}.layer:nth-child(1) strong{color:var(--blue)}.layer:nth-child(2) strong{color:var(--green)}.layer:nth-child(3) strong{color:var(--yellow)}.layer:nth-child(4) strong{color:var(--purple)}.layer:nth-child(5) strong{color:var(--pink)}.layer:nth-child(6) strong{color:var(--orange)}
.trade-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.deriv{border-left:3px solid var(--yellow)}.options{border-left:3px solid var(--pink)}.isolate{border-left:3px solid var(--green)}.check{border-left:3px solid var(--blue)}.refresh{color:var(--blue);text-shadow:0 0 12px #24d8ff55}.footer{margin-top:30px;padding:18px 0;border-top:1px solid #28304d;display:flex;justify-content:space-between;color:#66708f;font-size:9px;letter-spacing:.15em}.footer b{color:#9aa5c9}.footer .psy{color:var(--pink)}
@media(max-width:850px){.grid,.trade-grid{grid-template-columns:repeat(2,1fr)}.layers{grid-template-columns:repeat(3,1fr)}.hero:after{opacity:.35;right:-100px}.market-grid{grid-template-columns:1fr}}@media(max-width:520px){.wrap{padding:14px}.top{align-items:flex-start}.brand{font-size:16px}.status{font-size:8px;padding:8px 10px}.hero{padding:38px 0 28px}.hero h1{font-size:48px}.hero:after{display:none}.grid,.trade-grid{grid-template-columns:1fr 1fr}.value{font-size:19px}.price{font-size:32px}.layers{grid-template-columns:repeat(2,1fr)}.footer{display:block;line-height:2.1}.footer span{display:block}}
</style>
</head>
<body>
<div class="wrap">
<header class="top"><div><div class="brand">PSYCHO <span>//</span> MARKET BRIDGE</div><div class="sub">PHASE 2 — MARKET STRUCTURE ENGINE</div></div><div class="status"><span class="dot"></span><span id="bridge">BRIDGE ONLINE</span></div></header>
<section class="hero"><div class="eyebrow">◈ LIVE MARKET INTELLIGENCE INFRASTRUCTURE</div><h1><span class="hot">READ THE</span><br><span class="outline">MARKET.</span></h1><p>Where raw market flow enters the PSYCHO architecture. DHAN supplies the feed. The bridge isolates the session and exposes the structure required by Phase 2.</p><div class="pulse"></div></section>
<section class="grid">
<div class="card"><div class="label">Market state</div><div class="value state" id="market">—</div><div class="small" id="reason">—</div></div>
<div class="card"><div class="label">Live window</div><div class="value">09:15—15:40</div><div class="small">IST • NSE session</div></div>
<div class="card"><div class="label">Refresh cycle</div><div class="value">60 SEC</div><div class="small">automatic live acquisition</div></div>
<div class="card"><div class="label">Feed origin</div><div class="value" style="color:var(--blue)">DHAN</div><div class="small">server-side market feed</div></div>
</section>
<section class="section"><div class="section-title">◈ UNDERLYING MARKET PULSE</div><div class="market-grid">
<div class="card market nifty"><div class="market-head"><div class="ticker">NIFTY <span class="spark">✦</span></div><div class="pill" id="nstatus">WAITING</div></div><div class="price" id="nprice">—</div><div class="gap" id="ngap">GAP —</div><div class="row"><div class="mini"><div class="label">1M MICRO</div><b id="n1">0</b></div><div class="mini"><div class="label">5M FLOW</div><b id="n5">0</b></div><div class="mini"><div class="label">15M STRUCTURE</div><b id="n15">0</b></div></div></div>
<div class="card market bank"><div class="market-head"><div class="ticker">BANK NIFTY <span class="spark">✦</span></div><div class="pill" id="bstatus">WAITING</div></div><div class="price" id="bprice">—</div><div class="gap" id="bgap">GAP —</div><div class="row"><div class="mini"><div class="label">1M MICRO</div><b id="b1">0</b></div><div class="mini"><div class="label">5M FLOW</div><b id="b5">0</b></div><div class="mini"><div class="label">15M STRUCTURE</div><b id="b15">0</b></div></div></div>
</div></section>
<section class="section"><div class="section-title">◈ MULTI-TIMEFRAME RADAR</div><div class="layers"><div class="layer"><strong>1M</strong><span>MICRO</span></div><div class="layer"><strong>5M</strong><span>EXECUTION</span></div><div class="layer"><strong>15M</strong><span>STRUCTURE</span></div><div class="layer"><strong>1H</strong><span>CONTEXT</span></div><div class="layer"><strong>1D</strong><span>DAILY</span></div><div class="layer"><strong>1W</strong><span>MACRO</span></div></div></section>
<section class="section"><div class="section-title">◈ DERIVATIVE INTELLIGENCE</div><div class="trade-grid"><div class="card deriv"><div class="label">Futures</div><div class="value" style="color:var(--yellow)">FUTURES</div><div class="small">Nearest index future • 5M OHLCV/OI • live quote • 5-level depth</div></div><div class="card options"><div class="label">Options</div><div class="value" style="color:var(--pink)">ATM ± 10</div><div class="small">Nearest expiry • CE/PE • OI • volume • IV • Greeks • bid/ask</div></div><div class="card isolate"><div class="label">Session policy</div><div class="value" style="color:var(--green)">ISOLATED</div><div class="small">Current-day intraday data remains separated from previous-session intraday data</div></div><div class="card check"><div class="label">Last server check</div><div class="value refresh" id="checked">—</div><div class="small">Dashboard refreshes automatically</div></div></div></section>
<footer class="footer"><span><b class="psy">PSYCHO</b> TRADING // PHASE 2</span><span>DHAN → <b>BRIDGE</b> → STRUCTURE ENGINE</span></footer>
</div>
<script>
const $=id=>document.getElementById(id);const fmt=v=>v==null?'—':Number(v).toLocaleString('en-IN',{maximumFractionDigits:2});
async function pull(){try{const s=await fetch('/bridge-status',{cache:'no-store'}).then(r=>r.json());$('bridge').textContent=s.server==='ONLINE'?'BRIDGE ONLINE':'BRIDGE CHECK';$('market').textContent=s.market?.status||'—';$('reason').textContent=s.market?.reason||'—';$('checked').textContent=new Date().toLocaleTimeString('en-IN',{hour12:false});const load=async(k,p)=>{try{const d=await fetch(p,{cache:'no-store'}).then(r=>r.json());const m=d.market||{};const c=m.current_session||{};const t=m.timeframes||{};$(k+'status').textContent=d.status||'WAITING';$(k+'price').textContent=fmt(c.last_price);$(k+'gap').textContent='GAP '+(c.gap?.type||'—')+' '+(c.gap?.points??'');$(k+'1').textContent=(t['1M']||[]).length;$(k+'5').textContent=(t['5M']||[]).length;$(k+'15').textContent=(t['15M']||[]).length}catch(e){}};await load('n','/nifty-live');await load('b','/banknifty-live')}catch(e){$('bridge').textContent='BRIDGE UNREACHABLE'}}pull();setInterval(pull,15000);
</script>
</body></html>'''


@app.route("/")
def psycho_home():
    return Response(PSYCHO_HTML, content_type="text/html; charset=utf-8")


if __name__ == "__main__":
    threading.Thread(target=live_refresh_worker, daemon=True, name="psycho-live-refresh").start()
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port, threaded=True, use_reloader=False)
